<?php
//Initialize some data
$occupations = elgg_list_entities(array(
        'types' => 'object',
        'subtypes' => 'occupation',
        'full_view' => FALSE,
));
foreach ($occupations as $occupation) {
        $occupation->delete();
}

$occupation[0] = new ElggObject();
$occupation[0]->subtype="occupation";
$occupation[0]->label=" Accountant / Auditor";
$occupation[0]->save();
$occupation[1] = new ElggObject();
$occupation[1]->subtype="occupation";
$occupation[1]->label=" Accounts Manager";
$occupation[1]->save();
$occupation[2] = new ElggObject();
$occupation[2]->subtype="occupation";
$occupation[2]->label=" Administration Coordinator";
$occupation[2]->save();
$occupation[3] = new ElggObject();
$occupation[3]->subtype="occupation";
$occupation[3]->label=" Administrative Manager";
$occupation[3]->save();
$occupation[4] = new ElggObject();
$occupation[4]->subtype="occupation";
$occupation[4]->label=" Administrative researcher";
$occupation[4]->save();
$occupation[5] = new ElggObject();
$occupation[5]->subtype="occupation";
$occupation[5]->label=" Agricultural specialist";
$occupation[5]->save();
$occupation[6] = new ElggObject();
$occupation[6]->subtype="occupation";
$occupation[6]->label=" Air Controller";
$occupation[6]->save();
$occupation[7] = new ElggObject();
$occupation[7]->subtype="occupation";
$occupation[7]->label=" Aircraft Landing Controller";
$occupation[7]->save();
$occupation[8] = new ElggObject();
$occupation[8]->subtype="occupation";
$occupation[8]->label=" Aircraft maintenance technician";
$occupation[8]->save();
$occupation[9] = new ElggObject();
$occupation[9]->subtype="occupation";
$occupation[9]->label=" Aircraft Pilot";
$occupation[9]->save();
$occupation[10] = new ElggObject();
$occupation[10]->subtype="occupation";
$occupation[10]->label=" Aircraft Takeoff Controller";
$occupation[10]->save();
$occupation[11] = new ElggObject();
$occupation[11]->subtype="occupation";
$occupation[11]->label=" Air Hostess";
$occupation[11]->save();
$occupation[12] = new ElggObject();
$occupation[12]->subtype="occupation";
$occupation[12]->label=" Air Transport Manager";
$occupation[12]->save();
$occupation[13] = new ElggObject();
$occupation[13]->subtype="occupation";
$occupation[13]->label=" Aquatic specialist";
$occupation[13]->save();
$occupation[14] = new ElggObject();
$occupation[14]->subtype="occupation";
$occupation[14]->label=" Archeological Director";
$occupation[14]->save();
$occupation[15] = new ElggObject();
$occupation[15]->subtype="occupation";
$occupation[15]->label=" Archeological Prospector";
$occupation[15]->save();
$occupation[16] = new ElggObject();
$occupation[16]->subtype="occupation";
$occupation[16]->label=" Archeological researcher";
$occupation[16]->save();
$occupation[17] = new ElggObject();
$occupation[17]->subtype="occupation";
$occupation[17]->label=" Architectural draftsman";
$occupation[17]->save();
$occupation[18] = new ElggObject();
$occupation[18]->subtype="occupation";
$occupation[18]->label=" Army officer";
$occupation[18]->save();
$occupation[19] = new ElggObject();
$occupation[19]->subtype="occupation";
$occupation[19]->label=" Artist (Actor, Musician, Composer, Poet, Painter, Singer…..etc)";
$occupation[19]->save();
$occupation[20] = new ElggObject();
$occupation[20]->subtype="occupation";
$occupation[20]->label=" Assistant Engineer (All specializations)";
$occupation[20]->save();
$occupation[21] = new ElggObject();
$occupation[21]->subtype="occupation";
$occupation[21]->label=" Assistant General Manager";
$occupation[21]->save();
$occupation[22] = new ElggObject();
$occupation[22]->subtype="occupation";
$occupation[22]->label=" Assistant Pharmacist";
$occupation[22]->save();
$occupation[23] = new ElggObject();
$occupation[23]->subtype="occupation";
$occupation[23]->label=" Astronomer";
$occupation[23]->save();
$occupation[24] = new ElggObject();
$occupation[24]->subtype="occupation";
$occupation[24]->label=" Author";
$occupation[24]->save();
$occupation[25] = new ElggObject();
$occupation[25]->subtype="occupation";
$occupation[25]->label=" Aviation Guide";
$occupation[25]->save();
$occupation[26] = new ElggObject();
$occupation[26]->subtype="occupation";
$occupation[26]->label=" Aviation Technician";
$occupation[26]->save();
$occupation[27] = new ElggObject();
$occupation[27]->subtype="occupation";
$occupation[27]->label=" Aviation Trainer";
$occupation[27]->save();
$occupation[28] = new ElggObject();
$occupation[28]->subtype="occupation";
$occupation[28]->label=" Banker";
$occupation[28]->save();
$occupation[29] = new ElggObject();
$occupation[29]->subtype="occupation";
$occupation[29]->label=" Banking business Manager";
$occupation[29]->save();
$occupation[30] = new ElggObject();
$occupation[30]->subtype="occupation";
$occupation[30]->label=" Bank Manager";
$occupation[30]->save();
$occupation[31] = new ElggObject();
$occupation[31]->subtype="occupation";
$occupation[31]->label=" Breeding specialist (animals/birds/bees)";
$occupation[31]->save();
$occupation[32] = new ElggObject();
$occupation[32]->subtype="occupation";
$occupation[32]->label=" Broadcasting Manager";
$occupation[32]->save();
$occupation[33] = new ElggObject();
$occupation[33]->subtype="occupation";
$occupation[33]->label=" Business lady";
$occupation[33]->save();
$occupation[34] = new ElggObject();
$occupation[34]->subtype="occupation";
$occupation[34]->label=" Businessman";
$occupation[34]->save();
$occupation[35] = new ElggObject();
$occupation[35]->subtype="occupation";
$occupation[35]->label=" Captain";
$occupation[35]->save();
$occupation[36] = new ElggObject();
$occupation[36]->subtype="occupation";
$occupation[36]->label=" Captain of Ship/Cruise/Carrier/Steamship";
$occupation[36]->save();
$occupation[37] = new ElggObject();
$occupation[37]->subtype="occupation";
$occupation[37]->label=" Career Counselor";
$occupation[37]->save();
$occupation[38] = new ElggObject();
$occupation[38]->subtype="occupation";
$occupation[38]->label=" Chemist (All Specializations)";
$occupation[38]->save();
$occupation[39] = new ElggObject();
$occupation[39]->subtype="occupation";
$occupation[39]->label=" Chief Justice";
$occupation[39]->save();
$occupation[40] = new ElggObject();
$occupation[40]->subtype="occupation";
$occupation[40]->label=" Cinema Cameraman";
$occupation[40]->save();
$occupation[41] = new ElggObject();
$occupation[41]->subtype="occupation";
$occupation[41]->label=" Cinema Director";
$occupation[41]->save();
$occupation[42] = new ElggObject();
$occupation[42]->subtype="occupation";
$occupation[42]->label=" Cinema or Television Producer";
$occupation[42]->save();
$occupation[43] = new ElggObject();
$occupation[43]->subtype="occupation";
$occupation[43]->label=" College dean";
$occupation[43]->save();
$occupation[44] = new ElggObject();
$occupation[44]->subtype="occupation";
$occupation[44]->label=" Commercial Broker";
$occupation[44]->save();
$occupation[45] = new ElggObject();
$occupation[45]->subtype="occupation";
$occupation[45]->label=" Commercial Manager";
$occupation[45]->save();
$occupation[46] = new ElggObject();
$occupation[46]->subtype="occupation";
$occupation[46]->label=" Company or Factory Manager";
$occupation[46]->save();
$occupation[47] = new ElggObject();
$occupation[47]->subtype="occupation";
$occupation[47]->label=" Computer Programmer";
$occupation[47]->save();
$occupation[48] = new ElggObject();
$occupation[48]->subtype="occupation";
$occupation[48]->label=" Consultant";
$occupation[48]->save();
$occupation[49] = new ElggObject();
$occupation[49]->subtype="occupation";
$occupation[49]->label=" Control equipments technician";
$occupation[49]->save();
$occupation[50] = new ElggObject();
$occupation[50]->subtype="occupation";
$occupation[50]->label=" Cooperative Society Manager";
$occupation[50]->save();
$occupation[51] = new ElggObject();
$occupation[51]->subtype="occupation";
$occupation[51]->label=" Co-Pilot";
$occupation[51]->save();
$occupation[52] = new ElggObject();
$occupation[52]->subtype="occupation";
$occupation[52]->label=" Correspondent (Newspaper/Radio/TV)";
$occupation[52]->save();
$occupation[53] = new ElggObject();
$occupation[53]->subtype="occupation";
$occupation[53]->label=" Cruise Ship Guide";
$occupation[53]->save();
$occupation[54] = new ElggObject();
$occupation[54]->subtype="occupation";
$occupation[54]->label=" Customs Clearer";
$occupation[54]->save();
$occupation[55] = new ElggObject();
$occupation[55]->subtype="occupation";
$occupation[55]->label=" Customs specialist";
$occupation[55]->save();
$occupation[56] = new ElggObject();
$occupation[56]->subtype="occupation";
$occupation[56]->label=" Decoration Designer";
$occupation[56]->save();
$occupation[57] = new ElggObject();
$occupation[57]->subtype="occupation";
$occupation[57]->label=" Dental technician (fixing)";
$occupation[57]->save();
$occupation[58] = new ElggObject();
$occupation[58]->subtype="occupation";
$occupation[58]->label=" Diplomat (Members of diplomatic corps)";
$occupation[58]->save();
$occupation[59] = new ElggObject();
$occupation[59]->subtype="occupation";
$occupation[59]->label=" Director";
$occupation[59]->save();
$occupation[60] = new ElggObject();
$occupation[60]->subtype="occupation";
$occupation[60]->label=" Earthquakes expert";
$occupation[60]->save();
$occupation[61] = new ElggObject();
$occupation[61]->subtype="occupation";
$occupation[61]->label=" ECG technician";
$occupation[61]->save();
$occupation[62] = new ElggObject();
$occupation[62]->subtype="occupation";
$occupation[62]->label=" Economic Analyst";
$occupation[62]->save();
$occupation[63] = new ElggObject();
$occupation[63]->subtype="occupation";
$occupation[63]->label=" Electrical Manager";
$occupation[63]->save();
$occupation[64] = new ElggObject();
$occupation[64]->subtype="occupation";
$occupation[64]->label=" Engineer (All specializations)";
$occupation[64]->save();
$occupation[65] = new ElggObject();
$occupation[65]->subtype="occupation";
$occupation[65]->label=" Executive Manager / Director";
$occupation[65]->save();
$occupation[66] = new ElggObject();
$occupation[66]->subtype="occupation";
$occupation[66]->label=" Executive secretary";
$occupation[66]->save();
$occupation[67] = new ElggObject();
$occupation[67]->subtype="occupation";
$occupation[67]->label=" Finance/Economics expert";
$occupation[67]->save();
$occupation[68] = new ElggObject();
$occupation[68]->subtype="occupation";
$occupation[68]->label=" Finance Manager";
$occupation[68]->save();
$occupation[69] = new ElggObject();
$occupation[69]->subtype="occupation";
$occupation[69]->label=" Food Controller";
$occupation[69]->save();
$occupation[70] = new ElggObject();
$occupation[70]->subtype="occupation";
$occupation[70]->label=" Foodstuff technician";
$occupation[70]->save();
$occupation[71] = new ElggObject();
$occupation[71]->subtype="occupation";
$occupation[71]->label=" Gardening specialist";
$occupation[71]->save();
$occupation[72] = new ElggObject();
$occupation[72]->subtype="occupation";
$occupation[72]->label=" General Professional Trainer (Industrial/Agricultural/Commercial)";
$occupation[72]->save();
$occupation[73] = new ElggObject();
$occupation[73]->subtype="occupation";
$occupation[73]->label=" General Supervisor";
$occupation[73]->save();
$occupation[74] = new ElggObject();
$occupation[74]->subtype="occupation";
$occupation[74]->label=" Geologist";
$occupation[74]->save();
$occupation[75] = new ElggObject();
$occupation[75]->subtype="occupation";
$occupation[75]->label=" Geology technician";
$occupation[75]->save();
$occupation[76] = new ElggObject();
$occupation[76]->subtype="occupation";
$occupation[76]->label=" Head of Prosecution";
$occupation[76]->save();
$occupation[77] = new ElggObject();
$occupation[77]->subtype="occupation";
$occupation[77]->label=" Horse breeding technician";
$occupation[77]->save();
$occupation[78] = new ElggObject();
$occupation[78]->subtype="occupation";
$occupation[78]->label=" Hospital Manager";
$occupation[78]->save();
$occupation[79] = new ElggObject();
$occupation[79]->subtype="occupation";
$occupation[79]->label=" Hotel Manager";
$occupation[79]->save();
$occupation[80] = new ElggObject();
$occupation[80]->subtype="occupation";
$occupation[80]->label=" Information Systems expert";
$occupation[80]->save();
$occupation[81] = new ElggObject();
$occupation[81]->subtype="occupation";
$occupation[81]->label=" Institute Manager";
$occupation[81]->save();
$occupation[82] = new ElggObject();
$occupation[82]->subtype="occupation";
$occupation[82]->label=" Insurance Manager";
$occupation[82]->save();
$occupation[83] = new ElggObject();
$occupation[83]->subtype="occupation";
$occupation[83]->label=" Investment Manager";
$occupation[83]->save();
$occupation[84] = new ElggObject();
$occupation[84]->subtype="occupation";
$occupation[84]->label=" Jeweler";
$occupation[84]->save();
$occupation[85] = new ElggObject();
$occupation[85]->subtype="occupation";
$occupation[85]->label=" Journalist";
$occupation[85]->save();
$occupation[86] = new ElggObject();
$occupation[86]->subtype="occupation";
$occupation[86]->label=" Judge";
$occupation[86]->save();
$occupation[87] = new ElggObject();
$occupation[87]->subtype="occupation";
$occupation[87]->label=" Laboratory Manager";
$occupation[87]->save();
$occupation[88] = new ElggObject();
$occupation[88]->subtype="occupation";
$occupation[88]->label=" Lab specialist";
$occupation[88]->save();
$occupation[89] = new ElggObject();
$occupation[89]->subtype="occupation";
$occupation[89]->label=" Lab Technician";
$occupation[89]->save();
$occupation[90] = new ElggObject();
$occupation[90]->subtype="occupation";
$occupation[90]->label=" Land Hostess";
$occupation[90]->save();
$occupation[91] = new ElggObject();
$occupation[91]->subtype="occupation";
$occupation[91]->label=" Land Transport Manager";
$occupation[91]->save();
$occupation[92] = new ElggObject();
$occupation[92]->subtype="occupation";
$occupation[92]->label=" Law expert";
$occupation[92]->save();
$occupation[93] = new ElggObject();
$occupation[93]->subtype="occupation";
$occupation[93]->label=" Lawyer / Advocate";
$occupation[93]->save();
$occupation[94] = new ElggObject();
$occupation[94]->subtype="occupation";
$occupation[94]->label=" Lecturer";
$occupation[94]->save();
$occupation[95] = new ElggObject();
$occupation[95]->subtype="occupation";
$occupation[95]->label=" Legal researcher";
$occupation[95]->save();
$occupation[96] = new ElggObject();
$occupation[96]->subtype="occupation";
$occupation[96]->label=" Library Manager";
$occupation[96]->save();
$occupation[97] = new ElggObject();
$occupation[97]->subtype="occupation";
$occupation[97]->label=" Maintenance Manager";
$occupation[97]->save();
$occupation[98] = new ElggObject();
$occupation[98]->subtype="occupation";
$occupation[98]->label=" Male or Female Nurse";
$occupation[98]->save();
$occupation[99] = new ElggObject();
$occupation[99]->subtype="occupation";
$occupation[99]->label=" Manager or Director of any government departments or companies";
$occupation[99]->save();
$occupation[100] = new ElggObject();
$occupation[100]->subtype="occupation";
$occupation[100]->label=" Marine Traffic Controller";
$occupation[100]->save();
$occupation[101] = new ElggObject();
$occupation[101]->subtype="occupation";
$occupation[101]->label=" Marine Transport Manager";
$occupation[101]->save();
$occupation[102] = new ElggObject();
$occupation[102]->subtype="occupation";
$occupation[102]->label=" Maritime Controller";
$occupation[102]->save();
$occupation[103] = new ElggObject();
$occupation[103]->subtype="occupation";
$occupation[103]->label=" Marketing Manager";
$occupation[103]->save();
$occupation[104] = new ElggObject();
$occupation[104]->subtype="occupation";
$occupation[104]->label=" Marketing Representative";
$occupation[104]->save();
$occupation[105] = new ElggObject();
$occupation[105]->subtype="occupation";
$occupation[105]->label=" Media Controller";
$occupation[105]->save();
$occupation[106] = new ElggObject();
$occupation[106]->subtype="occupation";
$occupation[106]->label=" Media Manager";
$occupation[106]->save();
$occupation[107] = new ElggObject();
$occupation[107]->subtype="occupation";
$occupation[107]->label=" Media person";
$occupation[107]->save();
$occupation[108] = new ElggObject();
$occupation[108]->subtype="occupation";
$occupation[108]->label=" Media specialist";
$occupation[108]->save();
$occupation[109] = new ElggObject();
$occupation[109]->subtype="occupation";
$occupation[109]->label=" Medical analysis specialist";
$occupation[109]->save();
$occupation[110] = new ElggObject();
$occupation[110]->subtype="occupation";
$occupation[110]->label=" Medical equipments technician";
$occupation[110]->save();
$occupation[111] = new ElggObject();
$occupation[111]->subtype="occupation";
$occupation[111]->label=" Medical therapy specialist";
$occupation[111]->save();
$occupation[112] = new ElggObject();
$occupation[112]->subtype="occupation";
$occupation[112]->label=" Medical X-ray specialist";
$occupation[112]->save();
$occupation[113] = new ElggObject();
$occupation[113]->subtype="occupation";
$occupation[113]->label=" Microscopic technician";
$occupation[113]->save();
$occupation[114] = new ElggObject();
$occupation[114]->subtype="occupation";
$occupation[114]->label=" Mining technician";
$occupation[114]->save();
$occupation[115] = new ElggObject();
$occupation[115]->subtype="occupation";
$occupation[115]->label=" Ministry Undersecretary";
$occupation[115]->save();
$occupation[116] = new ElggObject();
$occupation[116]->subtype="occupation";
$occupation[116]->label=" Museum Manager";
$occupation[116]->save();
$occupation[117] = new ElggObject();
$occupation[117]->subtype="occupation";
$occupation[117]->label=" Nutrition specialist";
$occupation[117]->save();
$occupation[118] = new ElggObject();
$occupation[118]->subtype="occupation";
$occupation[118]->label=" Operations Analyst";
$occupation[118]->save();
$occupation[119] = new ElggObject();
$occupation[119]->subtype="occupation";
$occupation[119]->label=" Optical technician";
$occupation[119]->save();
$occupation[120] = new ElggObject();
$occupation[120]->subtype="occupation";
$occupation[120]->label=" Pharmaceutical technician";
$occupation[120]->save();
$occupation[121] = new ElggObject();
$occupation[121]->subtype="occupation";
$occupation[121]->label=" Pharmacist";
$occupation[121]->save();
$occupation[122] = new ElggObject();
$occupation[122]->subtype="occupation";
$occupation[122]->label=" Physician (All specialisation)";
$occupation[122]->save();
$occupation[123] = new ElggObject();
$occupation[123]->subtype="occupation";
$occupation[123]->label=" Physicist";
$occupation[123]->save();
$occupation[124] = new ElggObject();
$occupation[124]->subtype="occupation";
$occupation[124]->label=" Pilot";
$occupation[124]->save();
$occupation[125] = new ElggObject();
$occupation[125]->subtype="occupation";
$occupation[125]->label=" Plant Manager";
$occupation[125]->save();
$occupation[126] = new ElggObject();
$occupation[126]->subtype="occupation";
$occupation[126]->label=" Player (All sports items in a sports club)";
$occupation[126]->save();
$occupation[127] = new ElggObject();
$occupation[127]->subtype="occupation";
$occupation[127]->label=" Police officer";
$occupation[127]->save();
$occupation[128] = new ElggObject();
$occupation[128]->subtype="occupation";
$occupation[128]->label=" President/CEO";
$occupation[128]->save();
$occupation[129] = new ElggObject();
$occupation[129]->subtype="occupation";
$occupation[129]->label=" President or director of a club";
$occupation[129]->save();
$occupation[130] = new ElggObject();
$occupation[130]->subtype="occupation";
$occupation[130]->label=" President or director of a university";
$occupation[130]->save();
$occupation[131] = new ElggObject();
$occupation[131]->subtype="occupation";
$occupation[131]->label=" Press Photographer";
$occupation[131]->save();
$occupation[132] = new ElggObject();
$occupation[132]->subtype="occupation";
$occupation[132]->label=" Printing and Publishing Manager";
$occupation[132]->save();
$occupation[133] = new ElggObject();
$occupation[133]->subtype="occupation";
$occupation[133]->label=" Procurement Representative";
$occupation[133]->save();
$occupation[134] = new ElggObject();
$occupation[134]->subtype="occupation";
$occupation[134]->label=" Production Director";
$occupation[134]->save();
$occupation[135] = new ElggObject();
$occupation[135]->subtype="occupation";
$occupation[135]->label=" Professional security and safety technician";
$occupation[135]->save();
$occupation[136] = new ElggObject();
$occupation[136]->subtype="occupation";
$occupation[136]->label=" Professor";
$occupation[136]->save();
$occupation[137] = new ElggObject();
$occupation[137]->subtype="occupation";
$occupation[137]->label=" Program Producer";
$occupation[137]->save();
$occupation[138] = new ElggObject();
$occupation[138]->subtype="occupation";
$occupation[138]->label=" Proofreader";
$occupation[138]->save();
$occupation[139] = new ElggObject();
$occupation[139]->subtype="occupation";
$occupation[139]->label=" Prosecutor";
$occupation[139]->save();
$occupation[140] = new ElggObject();
$occupation[140]->subtype="occupation";
$occupation[140]->label=" Psychiatrist";
$occupation[140]->save();
$occupation[141] = new ElggObject();
$occupation[141]->subtype="occupation";
$occupation[141]->label=" Quality Controller";
$occupation[141]->save();
$occupation[142] = new ElggObject();
$occupation[142]->subtype="occupation";
$occupation[142]->label=" Quantity enumerator";
$occupation[142]->save();
$occupation[143] = new ElggObject();
$occupation[143]->subtype="occupation";
$occupation[143]->label=" Radio or TV transmission technician";
$occupation[143]->save();
$occupation[144] = new ElggObject();
$occupation[144]->subtype="occupation";
$occupation[144]->label=" Referee (sports)";
$occupation[144]->save();
$occupation[145] = new ElggObject();
$occupation[145]->subtype="occupation";
$occupation[145]->label=" Regional Director";
$occupation[145]->save();
$occupation[146] = new ElggObject();
$occupation[146]->subtype="occupation";
$occupation[146]->label=" Religious person";
$occupation[146]->save();
$occupation[147] = new ElggObject();
$occupation[147]->subtype="occupation";
$occupation[147]->label=" Research & Studies Director";
$occupation[147]->save();
$occupation[148] = new ElggObject();
$occupation[148]->subtype="occupation";
$occupation[148]->label=" Road Controller";
$occupation[148]->save();
$occupation[149] = new ElggObject();
$occupation[149]->subtype="occupation";
$occupation[149]->label=" Sales Manager";
$occupation[149]->save();
$occupation[150] = new ElggObject();
$occupation[150]->subtype="occupation";
$occupation[150]->label=" Sales Representative";
$occupation[150]->save();
$occupation[151] = new ElggObject();
$occupation[151]->subtype="occupation";
$occupation[151]->label=" School Manager";
$occupation[151]->save();
$occupation[152] = new ElggObject();
$occupation[152]->subtype="occupation";
$occupation[152]->label=" Scientist";
$occupation[152]->save();
$occupation[153] = new ElggObject();
$occupation[153]->subtype="occupation";
$occupation[153]->label=" Secretary or director of library";
$occupation[153]->save();
$occupation[154] = new ElggObject();
$occupation[154]->subtype="occupation";
$occupation[154]->label=" Ship Captain";
$occupation[154]->save();
$occupation[155] = new ElggObject();
$occupation[155]->subtype="occupation";
$occupation[155]->label=" Ship maintenance technician";
$occupation[155]->save();
$occupation[156] = new ElggObject();
$occupation[156]->subtype="occupation";
$occupation[156]->label=" Ships Supervisor";
$occupation[156]->save();
$occupation[157] = new ElggObject();
$occupation[157]->subtype="occupation";
$occupation[157]->label=" Sociologist";
$occupation[157]->save();
$occupation[158] = new ElggObject();
$occupation[158]->subtype="occupation";
$occupation[158]->label=" Speech specialist";
$occupation[158]->save();
$occupation[159] = new ElggObject();
$occupation[159]->subtype="occupation";
$occupation[159]->label=" Sports medicine specialist";
$occupation[159]->save();
$occupation[160] = new ElggObject();
$occupation[160]->subtype="occupation";
$occupation[160]->label=" Sports Representative";
$occupation[160]->save();
$occupation[161] = new ElggObject();
$occupation[161]->subtype="occupation";
$occupation[161]->label=" Sports Trainer";
$occupation[161]->save();
$occupation[162] = new ElggObject();
$occupation[162]->subtype="occupation";
$occupation[162]->label=" Staffs at embassies in GCC (except support services jobs)";
$occupation[162]->save();
$occupation[163] = new ElggObject();
$occupation[163]->subtype="occupation";
$occupation[163]->label=" Statistics specialist";
$occupation[163]->save();
$occupation[164] = new ElggObject();
$occupation[164]->subtype="occupation";
$occupation[164]->label=" Surgeon (All specialisation)";
$occupation[164]->save();
$occupation[165] = new ElggObject();
$occupation[165]->subtype="occupation";
$occupation[165]->label=" Surveyor";
$occupation[165]->save();
$occupation[166] = new ElggObject();
$occupation[166]->subtype="occupation";
$occupation[166]->label=" Systems Analyst";
$occupation[166]->save();
$occupation[167] = new ElggObject();
$occupation[167]->subtype="occupation";
$occupation[167]->label=" Teacher / Instructor";
$occupation[167]->save();
$occupation[168] = new ElggObject();
$occupation[168]->subtype="occupation";
$occupation[168]->label=" Telecom technician";
$occupation[168]->save();
$occupation[169] = new ElggObject();
$occupation[169]->subtype="occupation";
$occupation[169]->label=" Television Manager";
$occupation[169]->save();
$occupation[170] = new ElggObject();
$occupation[170]->subtype="occupation";
$occupation[170]->label=" Theatre Manager";
$occupation[170]->save();
$occupation[171] = new ElggObject();
$occupation[171]->subtype="occupation";
$occupation[171]->label=" Tourism Agency Manager";
$occupation[171]->save();
$occupation[172] = new ElggObject();
$occupation[172]->subtype="occupation";
$occupation[172]->label=" Tourist Guide";
$occupation[172]->save();
$occupation[173] = new ElggObject();
$occupation[173]->subtype="occupation";
$occupation[173]->label=" Trader";
$occupation[173]->save();
$occupation[174] = new ElggObject();
$occupation[174]->subtype="occupation";
$occupation[174]->label=" Train Maintenance Technician";
$occupation[174]->save();
$occupation[175] = new ElggObject();
$occupation[175]->subtype="occupation";
$occupation[175]->label=" Translator";
$occupation[175]->save();
$occupation[176] = new ElggObject();
$occupation[176]->subtype="occupation";
$occupation[176]->label=" Travel or Tourism Agent";
$occupation[176]->save();
$occupation[177] = new ElggObject();
$occupation[177]->subtype="occupation";
$occupation[177]->label=" TV Cameraman";
$occupation[177]->save();
$occupation[178] = new ElggObject();
$occupation[178]->subtype="occupation";
$occupation[178]->label=" TV or Radio Programs Presenter";
$occupation[178]->save();
$occupation[179] = new ElggObject();
$occupation[179]->subtype="occupation";
$occupation[179]->label=" University professor";
$occupation[179]->save();
$occupation[180] = new ElggObject();
$occupation[180]->subtype="occupation";
$occupation[180]->label=" University student";
$occupation[180]->save();
$occupation[181] = new ElggObject();
$occupation[181]->subtype="occupation";
$occupation[181]->label=" Veterinary doctor";
$occupation[181]->save();
$occupation[182] = new ElggObject();
$occupation[182]->subtype="occupation";
$occupation[182]->label=" Weather expert";
$occupation[182]->save();
$occupation[183] = new ElggObject();
$occupation[183]->subtype="occupation";
$occupation[183]->label=" Well drilling technician";
$occupation[183]->save();
$occupation[184] = new ElggObject();
$occupation[184]->subtype="occupation";
$occupation[184]->label=" Writer";
$occupation[184]->save();
$occupation[185] = new ElggObject();
$occupation[185]->subtype="occupation";
$occupation[185]->label=" X-Ray specialist";
$occupation[185]->save();
$occupation[186] = new ElggObject();
$occupation[186]->subtype="occupation";
$occupation[186]->label=" X-ray technician";
$occupation[186]->save();
$occupation[187] = new ElggObject();
$occupation[187]->subtype="occupation";
$occupation[187]->label=" Zoology specialist";
$occupation[187]->save();
